name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: T1 without data.txt
      id: t1-without-data-txt
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: T1 without data.txt
        setup-command: ''
        command: make clean && make test
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        T1-WITHOUT-DATA-TXT_RESULTS: "${{steps.t1-without-data-txt.outputs.result}}"
      with:
        runners: t1-without-data-txt
